# Numpy


Create a null vector of size 10.

In [11]:
import numpy as np

zeros = np.zeros(10)
zeros[4] = 1
print(zeros)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a 8x8 matrix and fill it with a checkerboard pattern.

In [15]:
board = np.zeros((8,8))
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print(board)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [18]:
np.random.random((5,5))

array([[0.60776999, 0.81595326, 0.52613015, 0.08013131, 0.37331856],
       [0.03038478, 0.73360358, 0.28565743, 0.00289186, 0.85655928],
       [0.22141548, 0.40945216, 0.93346699, 0.68315127, 0.66478883],
       [0.07079162, 0.11573598, 0.69307459, 0.05947122, 0.95046642],
       [0.22498682, 0.1360758 , 0.16300686, 0.59402368, 0.6166616 ]])